config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "books#index"

  get :search_book, to: 'books#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
require 'elasticsearch/model'


class Book < ApplicationRecord
	include Elasticsearch::Model
  	include Elasticsearch::Model::Callbacks

    # index_name [Rails.env, Rails.application.class.module_parent_name.underscore, self.name.downcase].join('_')

 #    settings index: { number_of_shards: 1 } do
	#     mappings do
	#         indexes :id, type: 'integer'
	#     end
	# end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def index
		@books = Book.limit(1000) 
	end
	
	def search
		starttime = Time.now
		@books =  if params[:with_elastic].present? && params[:with_elastic].eql?('true') 
			Book.search(params[:search_term]).records
		else
			Book.where("
				title ilike :search_term OR 
				author ilike :search_term OR 
				publisher ilike :search_term OR 
				genre ilike :search_term",
				search_term: "%#{params[:search_term].strip}%"
			)
		end 
		endtime = Time.now

		@time_took = (1000 * (endtime.to_f - starttime.to_f)).round(4)
		render :index
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<style>
table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {background-color: #f2f2f2;}

.search-with-elastic-section{
  width: 45%;
  display: inline-block;
  padding: 2%;
}
.search-without-elastic-section{
  width: 45%;
  display: inline-block;
  float: right;
  padding: 2%;
}
.search-section{
  padding-bottom: 17px;
}
.timing-section{
  padding: 2%;
  margin-bottom: 20px;
  text-align: center;
  font-size: 22px;
}
</style>



<div style="overflow-x: auto;">

  <% if @time_took.present? %>
    <fieldset class='timing-section'>
      <legend>Time Took to get result</legend>

      <div>
        <%= label_tag "#{@time_took} Miliseconds" %>
      </div>

    </fieldset>
  <% end %>

  <div class='search-section'>
    <fieldset class='search-with-elastic-section'>
      <legend>Search <b>with</b> ElasticSearch:</legend>
      <%= form_tag search_book_path, method: :get do %>
        <%= hidden_field_tag :with_elastic, true%>
        <%= label_tag 'Search Book' %>
        <%= text_field_tag :search_term, params[:search_term] %>
        <%= submit_tag 'Search'%>
      <% end %>
    </fieldset>

    <fieldset class='search-without-elastic-section'>
      <legend>Search <b>without</b> ElasticSearch:</legend>
      <%= form_tag search_book_path, method: :get do %>
        <%= label_tag 'Search Book' %>
        <%= text_field_tag :search_term, params[:search_term] %>
        <%= submit_tag 'Search'%>
      <% end %>
    </fieldset>
    
  </div>
  <table>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Publisher</th>
      <th>Genre</th>
    </tr>
    <% @books.each do|book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.publisher %></td>
        <td><%= book.genre %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookZone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>